name: Compilar APK

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos y compilar con Gradle Wrapper
        run: |
          cd android
          chmod +x gradlew || true
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --stacktrace --no-daemon
          else
            gradle assembleDebug --stacktrace --no-daemon
          fi

      - name: Guardar APK resultante
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "android/app/build/outputs/apk/debug/*.apk"
